version: '3.0'
services:
  rasa:
    image: rasa/rasa:2.3.1-full
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command:
      - run
  app:
    image: richardfelix/mecanix-chatbot:latest
    expose: 5055